IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'SeatDB')
BEGIN
    CREATE DATABASE SeatDB;
END
GO

USE SeatDB;
GO

IF OBJECT_ID('Employee', 'U') IS NOT NULL DROP TABLE Employee;
IF OBJECT_ID('SeatingChart', 'U') IS NOT NULL DROP TABLE SeatingChart;

CREATE TABLE SeatingChart (
	FLOOR_SEAT_SEQ INT PRIMARY KEY IDENTITY(1,1),
	FLOOR_NO INT NOT NULL,
	SEAT_NO INT NOT NULL
);

CREATE TABLE Employee (
	EMP_ID CHAR(5) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100),
	FLOOR_SEAT_SEQ INT,
	CONSTRAINT FK_Employee_SeatingChart
		FOREIGN KEY(FLOOR_SEAT_SEQ)
		REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);

CREATE UNIQUE INDEX UQ_Employee_Seat_Not_Null
ON Employee(FLOOR_SEAT_SEQ)
WHERE FLOOR_SEAT_SEQ IS NOT NULL;
GO